# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e69a6a1fb0b6dda662b52dd974bf9c8be51a1d32176da2a2312d76f32ade39cbb8daf5e5887450047ac4ee4ad5f8f9a234b9977525aac501481aa42347dd831

test:
  secret_key_base: 5726ef60e1d200343e055cbef33dec8647decdbb1b539042ce1f10a2c5de7fcf0b2cc0e9846a4604b68f2e1100c340e65a3c230344a25b2c501ea5f1344d11c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
